Fix login error: Convert Date to MySQL datetime format
The login was failing because updateUserLastSignIn was using ISO 8601 format
('2025-12-17T15:41:35.587Z') which MySQL rejects. Changed to MySQL datetime
format ('2025-12-17 15:41:35') by removing 'T', 'Z', and milliseconds.

Error: Incorrect datetime value: '2025-12-17T15:41:35.587Z' for column 'lastSignedIn'
Fixed: Now uses '2025-12-17 15:41:35' format